# Generated by Django 5.0.6 on 2024-07-09 11:50

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_uuid', models.CharField(max_length=5, unique=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
